---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build-latest-image
    image: plugins/docker
    settings:
      tags: latest
      repo: df17-140-112-179-52.jp.ngrok.io/web_frontend
      registry: df17-140-112-179-52.jp.ngrok.io
      dockerfile: Dockerfile_frontend
    when:
      event:
        - push

  - name: run-container
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.2.110
      port:
        - 22
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      script:
        docker rm --force web_frontend &&
        docker rmi df17-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
        docker pull df17-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
        docker run -d --name web_frontend -p 9999:80 df17-140-112-179-52.jp.ngrok.io/web_frontend:latest
    when:
      event:
        - push

  - name: build-version-image
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      repo: df17-140-112-179-52.jp.ngrok.io/web_frontend
      registry: df17-140-112-179-52.jp.ngrok.io
      dockerfile: Dockerfile_frontend
    when:
      event:
        - tag

  # - name: rollback-version-image
  #   image: appleboy/drone-ssh
  #   settings:
  #     host:
  #       - 192.168.2.110
  #     port:
  #       - 22
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #     script:
  #       docker pull df17-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
  #       docker rm --force web_frontend &&
  #       docker rmi df17-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
  #       docker run -d --name web_frontend -p 9999:80 df17-140-112-179-52.jp.ngrok.io/web_frontend:latest
  #   when:
  #     event:
  #       - rollback
