---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-image-push
  image: plugins/docker
  settings:
    repo: 331f-140-112-179-52.jp.ngrok.io/drone_test
    tags: latest
    registry: 331f-140-112-179-52.jp.ngrok.io
...