---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

# trigger:
#   event:
#   - tag

steps:
  # - name: build-image-push
  #   image: plugins/docker
  #   settings:
  #     tags: ${DRONE_TAG}
  #     repo: 3048-140-112-179-52.jp.ngrok.io/web_frontend
  #     registry: 3048-140-112-179-52.jp.ngrok.io
  #     dockerfile: Dockerfile_frontend

  - name: run-container
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.2.110
      port:
        - 22
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # command_timeout: 2m
      script:
        docker rm --force web_frontend
        docker rmi 3048-140-112-179-52.jp.ngrok.io/web_frontend:latest
        docker pull 3048-140-112-179-52.jp.ngrok.io/web_frontend:latest
        docker run -d --name web_frontend -p 9999:80 3048-140-112-179-52.jp.ngrok.io/web_frontend:latest
