---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker:dind
  commands:
  - docker build -f /home/Dockerfile_frontend --no-cache --tag 127.0.0.1:5000/drone_test:0.1 .
  - docker push 127.0.0.1:5000/drone_test:0.1
...