---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

# trigger:
#   event:
#   - tag

steps:
  - name: build-latest-image
    image: plugins/docker
    settings:
      tags: latest
      repo: 8a39-140-112-179-52.jp.ngrok.io/web_frontend
      registry: 8a39-140-112-179-52.jp.ngrok.io
      dockerfile: Dockerfile_frontend
    when:
      event:
        - push

  - name: run-container
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.2.110
      port:
        - 22
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # command_timeout: 2m
      script:
        docker rm --force web_frontend &&
        docker rmi 8a39-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
        docker pull 8a39-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
        docker run -d --name web_frontend -p 9999:80 8a39-140-112-179-52.jp.ngrok.io/web_frontend:latest
    when:
      event:
        - push

  - name: build-version-image
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      repo: 8a39-140-112-179-52.jp.ngrok.io/web_frontend
      registry: 8a39-140-112-179-52.jp.ngrok.io
      dockerfile: Dockerfile_frontend
    when:
      event:
        - tag

  - name: rollback-version-image
    image: appleboy/drone-ssh
    settings:
      host:
        - 192.168.2.110
      port:
        - 22
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      # command_timeout: 2m
      script:
        docker pull 8a39-140-112-179-52.jp.ngrok.io/web_frontend:${DRONE_TAG} &&
        docker rm --force web_frontend &&
        docker rmi 8a39-140-112-179-52.jp.ngrok.io/web_frontend:latest &&
        docker run -d --name web_frontend -p 9999:80 8a39-140-112-179-52.jp.ngrok.io/web_frontend:${DRONE_TAG}
    when:
      event:
        - rollback
