---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

# trigger:
#   event:
#   - tag

steps:
  # - name: build-image-push
  #   image: plugins/docker
  #   settings:
  #     tags: ${DRONE_TAG}
  #     repo: 3048-140-112-179-52.jp.ngrok.io/drone_test
  #     registry: 3048-140-112-179-52.jp.ngrok.io
  #     dockerfile: Dockerfile_frontend

  - name: run-container
    image: appleboy/drone-ssh
    # pull: true
    settings:
      host:
        - 192.168.0.128
      port:
        - 22
      username:
        from_secret: docker_username2
      password:
        from_secret: docker_password2
    # privileged: true
    script:
      - echo "fuck you"
    commands:
      - cd /home
      - ls -al
      - uname -a
      - ssh --help
      - docker --help
      # - docker rm --force drone_test
      # - docker rmi 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
      # - docker pull 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
      # - docker run -d --name  drone_test -p 9999:80 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
    # script:
    #   - docker --help
    #   - docker rm --force drone_test
    #   - docker rmi 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
    #   - docker pull 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
    #   - docker run -d --name  drone_test -p 9999:80 3048-140-112-179-52.jp.ngrok.io/drone_test:latest
