---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

# trigger:
#   event:
#   - tag

steps:
  - name: build-image-push
    image: plugins/docker
    settings:
      tags: ${DRONE_TAG}
      repo: 331f-140-112-179-52.jp.ngrok.io/drone_test
      registry: 331f-140-112-179-52.jp.ngrok.io
      dockerfile: Dockerfile_frontend

  - name: run-container
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm --force drone_test
      - docker pull 331f-140-112-179-52.jp.ngrok.io/drone_test:latest
      - docker run -d --name  drone_test -p 9999:80 331f-140-112-179-52.jp.ngrok.io/drone_test:latest
