---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

# trigger:
#   event:
#   - tag

steps:
  # - name: build-image-push
  #   image: plugins/docker
  #   settings:
  #     tags: ${DRONE_TAG}
  #     repo: 331f-140-112-179-52.jp.ngrok.io/drone_test
  #     registry: 331f-140-112-179-52.jp.ngrok.io
  #     dockerfile: Dockerfile_frontend

  - name: run-container
    image: appleboy/drone-ssh
    settings:
      host:
        - 127.0.0.1
      username: root
    # privileged: true
    script:
      - docker --help
      # - docker rmi 331f-140-112-179-52.jp.ngrok.io/drone_test:latest
      # - docker pull 331f-140-112-179-52.jp.ngrok.io/drone_test:latest
      # - docker run -d --name  drone_test -p 9999:80 331f-140-112-179-52.jp.ngrok.io/drone_test:latest
