version: "3"
services:
  drone-server:
    image: drone/drone:2.16.0
    container_name: drone.server
    restart: always
    ports:
      - 8880:80
    networks:
      - drone
    volumes:
      - /c/Users/ttl/.docker-desktop/drone:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      - TZ=Asia/Taipei
      - DRONE_SERVER_HOST=drone.thinktron.co
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=d00d424beb7cea21602f558d8b646d9b
      - DRONE_GITHUB_CLIENT_ID=304356fb1598ee6f58c0
      - DRONE_GITHUB_CLIENT_SECRET=a07bb48243b9d9240a1249352dd0541ca99442b1
      - DRONE_DEBUG=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TRACE=true
      - DRONE_USER_CREATE=admin:true

  drone-runner:
    image: drone/drone-runner-docker:1.8.2
    container_name: drone.runner
    restart: always
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 2G
    # depends_on:
    #   - drone-server
    environment:
      - TZ=Asia/Taipei
      - DRONE_RPC_HOST=drone.server
      - DRONE_RPC_SECRET=d00d424beb7cea21602f558d8b646d9b
      - DRONE_RPC_PROTO=http
      - DRONE_RUNNER_CAPACITY=5
      - DRONE_RUNNER_NAME=drone-docker-runner
      - DRONE_DEBUG=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TRACE=true

networks:
  drone:
    name: drone
    driver: bridge
